### ISSUE TITLE
facebook livestreaming

### ISSUE THREAD

**Issue by tajj** [leonidaxx90/FacebookLive4j#1]
Hello @leonidaxx90,

I am a developer trying to use facebook live's api on an android app. I noticed this app and the way you set it up and wanted to ask how exactly video stream is encoded into an rtmp stream and uploaded to an endpoint to connect it to facebook live.

Thank you!!

**Comment by leonidaxx90** [comment]
If you want to send the video stream to an endpoint you should use a rtmp client, such as wirecast or similar
