### ISSUE TITLE
path for url is not valid ( illegal character in path at index 0)

### ISSUE THREAD

**Issue by petreDanielMarian** [leonidaxx90/FacebookLive4j#2]
Hi, I was trying to use the api to stream a live video from my phone which sends the data to http://192.168.0.100:8080/video; i grab that video in java with vlcj and then I want to stream it over to facebook but i get the following error:
![image](https://user-images.githubusercontent.com/37928457/59224502-3a120600-8bd7-11e9-8779-0942484ee963.png)

My hierarchy is like this:
![image](https://user-images.githubusercontent.com/37928457/59224544-58780180-8bd7-11e9-9fe4-1be0e774f1db.png)

facebook.properties is in the root of the project and has its fields completed like this:
![image](https://user-images.githubusercontent.com/37928457/59224823-f66bcc00-8bd7-11e9-9135-ba8c227d7029.png)

BUT, there is another facebook.properties in the .jar i just uploaded:
![image](https://user-images.githubusercontent.com/37928457/59224676-a2f97e00-8bd7-11e9-8254-a90f338a899f.png)

which has the following fields:
![image](https://user-images.githubusercontent.com/37928457/59224713-b278c700-8bd7-11e9-909d-22ed70406875.png)

the thing is, the .properties that is not completed with valid info is dragged there by the .jar file and i cannot delete/edit it

Any idea if that is the root of my problem?
What i was trying to do was:
![image](https://user-images.githubusercontent.com/37928457/59224850-0683ab80-8bd8-11e9-928c-88de7ed0907b.png)

Thanks!

**Comment by leonidaxx90** [comment]
Hi @petreDanielMarian,

to solve this issue you should move your facebook.properties on root of project, on the same level of src folder (not inside it!). In this way code will read facebook.properties provided by you.

Best regards
